# Generated by Django 3.2.4 on 2021-07-23 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Category_images',
        ),
        migrations.AlterModelOptions(
            name='category_images',
            options={},
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='category',
            new_name='category_images',
        ),
    ]
