# Generated by Django 3.2.4 on 2021-07-24 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20210723_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_images',
            options={'verbose_name_plural': 'Category_images'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Galleries'},
        ),
    ]
